// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package todoItem

import (
	"database/sql"
	"time"
)

type Todoitem struct {
	ID          int64
	Title       string
	Detail      sql.NullString
	Completed   bool
	Starttime   time.Time
	Endtime     time.Time
	Createdtime sql.NullTime
	Updatedtime sql.NullTime
}
