// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package todoItem

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todoitem struct {
	ID          int64
	Title       string
	Detail      pgtype.Text
	Completed   bool
	Starttime   pgtype.Timestamp
	Endtime     pgtype.Timestamp
	Createdtime pgtype.Timestamp
	Updatedtime pgtype.Timestamp
}
